---
- name: Add group {{ group_name }}
  group:
    name: "{{ group_name }}"
    state: present
  become: true

- name: Add user accounts
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ group_name }},wheel"
  loop: "{{ user_accounts }}"
  become: true

- name: Generate SSH keys
  ansible.builtin.user:
    name: "{{ item.name }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: "~/.ssh/id_rsa"
    ssh_key_comment: "{{ item.ssh_key_comment }}"
  loop: "{{ user_accounts }}"

- name: Distribute ssh keys
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', '/mnt/c/Users/Brand/.ssh/id_rsa.pub')}}"
  loop: "{{ user_accounts }}"
