---
- name: Install Apache
  package:
    name: httpd
    state: present
  become: true

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: true
  become: true
  notify: Restart Apache
